"""
clean_transcripts.py

Cleans diarized transcripts generated by diarize.py:
  - Strips Claude API preamble (everything before the first speaker label)
  - Strips timestamps in formats like [00:04], [01:30:22], (00:04:22)
  - Joins multi-line speaker turns into single paragraphs
  - Preserves speaker labels in format [SPEAKER NAME - ROLE]:

Input:  samples/transcripts/diarized/<company>_diarized.txt
Output: samples/transcripts/clean/<company>_clean.txt

Usage:
    # Single company:
    python src/clean_transcripts.py amd

    # Multiple companies:
    python src/clean_transcripts.py amd ibm google

    # All 19 companies:
    python src/clean_transcripts.py --all
"""

import re
import sys
from pathlib import Path

DIARIZED_DIR = Path("samples/transcripts/diarized")
CLEAN_DIR = Path("samples/transcripts/clean")
SENTENCES_PER_PARAGRAPH = 10

COMPANIES = [
    "adobe-q2-fy26",
    "alibaba-q1-2026",
    "amazon-q1-2026",
    "amd-q1-2026",
    "asml-q1-2026",
    "broadcom-q1-2026",
    "cisco-q2-2026",
    "google-q1-2026",
    "ibm-q1-2026",
    "meta-q1-2026",
    "microsoft-q2-2026",
    "nvidia-q1-fy27",
    "oracle-q4-fy2026",
    "qualcomm-q2-2026",
    "salesforce-q1-fy27",
    "sandisk-q1-2026",
    "tesla-q1-2026",
    "ti-q3-2026-audio",
    "tsmc-q1-2026",
]

# Matches speaker labels like [JOHN - OPERATOR]: or [LISA SU - CEO]:
SPEAKER_LABEL_RE = re.compile(r"^\[.+?\]:")

# Matches timestamps in various formats:
# [00:04], [01:30:22], (00:04:22), [00:04:22]
TIMESTAMP_RE = re.compile(r"[\[\(]\d{1,2}:\d{2}(?::\d{2})?[\]\)]")


def clean_transcript(text: str) -> str:
    lines = text.splitlines()

    # Step 1: find the first speaker label line and strip everything before it
    start_idx = 0
    for i, line in enumerate(lines):
        if SPEAKER_LABEL_RE.match(line.strip()):
            start_idx = i
            break
    lines = lines[start_idx:]

    # Step 2: group lines by speaker turn
    # Each speaker label starts a new block; collect lines until the next label
    blocks = []
    current_label = None
    current_lines = []

    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        if SPEAKER_LABEL_RE.match(stripped):
            # Save previous block
            if current_label is not None:
                blocks.append((current_label, current_lines))
            # Start new block — split label from any inline text
            colon_idx = stripped.index("]:") + 2
            current_label = stripped[:colon_idx].strip()
            rest = stripped[colon_idx:].strip()
            current_lines = [rest] if rest else []
        else:
            # Strip timestamps from content lines
            cleaned = TIMESTAMP_RE.sub("", stripped).strip()
            if cleaned:
                current_lines.append(cleaned)

    # Save last block
    if current_label is not None:
        blocks.append((current_label, current_lines))

    # Step 3: build output — label, then content split into paragraphs of N sentences
    output_parts = []
    for label, content_lines in blocks:
        if not content_lines:
            continue

        # Join all lines into one string, clean double spaces
        full_text = " ".join(content_lines)
        full_text = re.sub(r" {2,}", " ", full_text).strip()
        if not full_text:
            continue

        # Split into sentences on ". ", "? ", "! "
        # Use re.split but keep the delimiter attached to the preceding sentence
        raw_sentences = re.split(r'(?<=[.?!])\s+', full_text)
        sentences = [s.strip() for s in raw_sentences if s.strip()]

        # Group into paragraphs of SENTENCES_PER_PARAGRAPH
        paragraphs = []
        for i in range(0, len(sentences), SENTENCES_PER_PARAGRAPH):
            chunk = sentences[i:i + SENTENCES_PER_PARAGRAPH]
            paragraphs.append(" ".join(chunk))

        body = "\n\n".join(paragraphs)
        output_parts.append(f"{label}\n{body}")

    return "\n\n".join(output_parts)


def find_diarized_file(company: str) -> Path:
    # Try exact match first
    path = DIARIZED_DIR / f"{company}_diarized.txt"
    if path.exists():
        return path
    # Try glob match for partial names
    candidates = list(DIARIZED_DIR.glob(f"{company}*_diarized.txt"))
    if candidates:
        return candidates[0]
    raise FileNotFoundError(f"No diarized file found for '{company}' in {DIARIZED_DIR}")


def process(company_stem: str) -> Path:
    source = find_diarized_file(company_stem)
    print(f"  Reading: {source.name}")

    text = source.read_text(encoding="utf-8")
    cleaned = clean_transcript(text)

    CLEAN_DIR.mkdir(parents=True, exist_ok=True)
    # Output filename: replace _diarized with _clean
    out_name = source.name.replace("_diarized.txt", "_clean.txt")
    output = CLEAN_DIR / out_name
    output.write_text(cleaned, encoding="utf-8")
    print(f"  Saved:   {output}")
    return output


def main():
    args = sys.argv[1:]
    if not args:
        print("Usage:")
        print("  python src/clean_transcripts.py amd")
        print("  python src/clean_transcripts.py amd ibm google")
        print("  python src/clean_transcripts.py --all")
        sys.exit(1)

    if args == ["--all"]:
        targets = COMPANIES
    else:
        targets = args

    print(f"Cleaning {len(targets)} transcript(s)...\n")
    success, failed = 0, []

    for company in targets:
        print(f"[{company}]")
        try:
            process(company)
            success += 1
        except Exception as e:
            print(f"  ERROR: {e}")
            failed.append(company)
        print()

    print(f"Done. {success} succeeded, {len(failed)} failed.")
    if failed:
        print(f"Failed: {', '.join(failed)}")


if __name__ == "__main__":
    main()