"""
diarize.py

Uses the Anthropic API (Claude Sonnet) to add speaker labels to a
Whisper-generated transcript. Claude uses web search to look up the
company's executive roster and analyst participants, then annotates
each speaker transition in the format [SPEAKER NAME - ROLE]:

Input:  samples/transcripts/whisper-or-extracted/<company>.txt
Output: samples/transcripts/diarized/<company>_diarized.txt

Usage:
    python src/diarize.py <company>
    python src/diarize.py amd
    python src/diarize.py oracle

    Batch (multiple companies):
    python src/diarize.py amd ibm meta google oracle

Special cases:
    TSMC transcript is mixed Chinese/English -- script handles this
    automatically based on company name.

Requires:
    pip install anthropic
    export ANTHROPIC_API_KEY="your-key-here"
"""

import sys
import os
import time
from pathlib import Path

import anthropic

TRANSCRIPTS_DIR = Path("samples/transcripts/whisper-or-extracted")
DIARIZED_DIR = Path("samples/transcripts/diarized")
MODEL = "claude-sonnet-4-6"
MAX_TOKENS = 32000

BASE_PROMPT = """You are a transcript annotator for earnings call recordings. Your task is to add speaker labels to the transcript below.

The transcript was generated by OpenAI Whisper speech-to-text and may contain minor transcription errors (e.g. misspelled names, mishearings). It does NOT already have speaker labels.

Earnings calls follow a predictable structure:
- An OPERATOR opens the call, explains logistics, and introduces the IR person
- The IR person (Investor Relations) welcomes attendees and introduces executives
- Executives (CEO, CFO, etc.) give prepared remarks
- During Q&A, analysts introduce themselves by name and firm, then ask questions
- Executives respond to each analyst question

You have access to web search. Use it to look up the company's executive team (CEO, CFO, IR head) at the time of the earnings call so you know exactly who to expect on the call. Also search for the list of analyst participants if available.

Your job:
1. Search the web for the company's executive roster and earnings call participant list
2. Read through the entire transcript
3. Identify speaker transitions based on context clues (introductions, "thank you", "our next question", name references, etc.)
4. Insert a speaker label at the start of each new speaker's turn in this format: [SPEAKER NAME - ROLE]:
5. If a speaker's name is unknown, use their role: [OPERATOR], [ANALYST], [CEO], [CFO] etc.
6. Do NOT change any of the transcript text itself -- only add speaker labels
7. Keep every word of the original transcript intact
8. If the transcript contains timestamps, keep them exactly as they appear
9. Correct obvious Whisper transcription errors in names only (e.g. if the transcript says "Cinder Pichai" but the actual CEO is Sundar Pichai, use the correct name in the label but leave the transcript text unchanged)

Return the full annotated transcript with speaker labels inserted.

TRANSCRIPT:
"""

TSMC_NOTE = """
NOTE: This transcript is mixed Chinese and English. The earnings call was conducted
primarily in English but some portions appear in Chinese characters due to the speech
recognition model transcribing Mandarin segments. Apply speaker labels to both language
sections using the same [SPEAKER NAME - ROLE]: format.

"""


def load_transcript(company: str):
    path = TRANSCRIPTS_DIR / f"{company}-q1-2026.txt"
    if not path.exists():
        candidates = list(TRANSCRIPTS_DIR.glob(f"{company}*.txt"))
        candidates = [c for c in candidates if "_diarized" not in c.name and "_wer" not in c.name]
        if not candidates:
            raise FileNotFoundError(f"No transcript found for '{company}' in {TRANSCRIPTS_DIR}")
        path = candidates[0]
        print(f"  Using: {path.name}")
    return path.read_text(encoding="utf-8"), path


def build_prompt(company: str, transcript: str) -> str:
    if company.lower() == "tsmc":
        return BASE_PROMPT + TSMC_NOTE + transcript
    return BASE_PROMPT + transcript


def diarize(company: str, client: anthropic.Anthropic) -> Path:
    print(f"\n{'='*50}")
    print(f"Processing: {company.upper()}")
    print(f"{'='*50}")

    transcript, source_path = load_transcript(company)
    print(f"  Transcript length: {len(transcript.split())} words")

    prompt = build_prompt(company, transcript)

    print(f"  Sending to Claude {MODEL}...")
    start = time.time()

    with client.messages.stream(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        tools=[{"type": "web_search_20250305", "name": "web_search"}],
        messages=[{"role": "user", "content": prompt}]
    ) as stream:
        for event in stream:
            pass
        message = stream.get_final_message()

    elapsed = time.time() - start
    print(f"  Done in {elapsed:.1f}s")

    text_blocks = [block.text for block in message.content if hasattr(block, "text")]
    result = "\n".join(text_blocks).strip()

    if not result:
        raise ValueError(f"No text content returned for {company}")

    DIARIZED_DIR.mkdir(parents=True, exist_ok=True)
    output_path = DIARIZED_DIR / f"{source_path.stem}_diarized.txt"
    output_path.write_text(result, encoding="utf-8")
    print(f"  Saved: {output_path}")

    return output_path


def main():
    if len(sys.argv) < 2:
        print("Usage: python src/diarize.py <company> [company2] [company3] ...")
        print("Example: python src/diarize.py amd ibm meta google oracle")
        sys.exit(1)

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("Error: ANTHROPIC_API_KEY environment variable not set.")
        print("Run: export ANTHROPIC_API_KEY='your-key-here'")
        sys.exit(1)

    client = anthropic.Anthropic(api_key=api_key)
    companies = sys.argv[1:]

    print(f"Diarizing {len(companies)} company transcript(s): {', '.join(companies)}")

    results = []
    for company in companies:
        try:
            output_path = diarize(company, client)
            results.append((company, "OK", str(output_path)))
        except Exception as e:
            print(f"  ERROR: {e}")
            results.append((company, "FAILED", str(e)))

    print(f"\n{'='*50}")
    print("SUMMARY")
    print(f"{'='*50}")
    for company, status, detail in results:
        print(f"  {company.upper():12} {status:8} {detail}")


if __name__ == "__main__":
    main()